# This is a basic workflow to help you get started with Actions

name: Build
on:
  push:
    branches:
      - main
      - release/*
    tags:
      - release/*
  pull_request:
    branches:
      - main
      - release/*

jobs:
  build:
    name: Build
    runs-on: windows-latest
    #url: https://github.com/actions/virtual-environments
    
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
        #url: https://github.com/actions/checkout

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

        
      - name: Configure .NET Core 3.1
        uses: actions/setup-dotnet@v1
        #url: https://github.com/actions/setup-dotnet
        with:
          dotnet-version: 3.1.x

#      - name: Configure .NET 4.6.1
#        uses: actions/setup-dotnet@v1
#        #url: https://github.com/actions/setup-dotnet
#        with:
#          dotnet-version: 4.6.x

      # Runs a single command using the runners shell
      - name: Rebuild the powershell module
        shell: pwsh
        run: 
          # PowerShell script 
          ./build.ps1 -Configuration 'Release'

      - name: Install gitversion as global tool
        shell: pwsh
        run: 
          # PowerShell script
          dotnet tool install --global GitVersion.Tool;

      - name: Save package
        shell: pwsh
        run: 
          # PowerShell script
          $MajorMinorPatch = (dotnet-gitversion | ConvertFrom-Json).MajorMinorPatch;
          ./packpackage.ps1 -Version $MajorMinorPatch;

      - run: echo ${{github.ref}}

      - name: Publish Package
        if: github.ref == 'refs/heads/main'
        shell: pwsh
        run:
          $nupkg = Get-ChildItem -Path "./out/nuget/*.nupkg" | Select-Object -First 1;
          dotnet nuget push $nupkg.FullName
          -s https://www.powershellgallery.com/
          -k $env:PSGALLERY_API_KEY
          --skip-duplicate
          --no-symbols 1
        env:
          PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
